#!/usr/bin/env python3
"""
Quick frequency lookup for Spanish lemmas and word forms.

Usage:
    python tools/frequency_lookup.py palabra [otra_palabra ...] [--tables subtlex,multilex]

Data source: data/frequency/frequency.sqlite (generated by scripts/build_frequency_index.py)
"""

from __future__ import annotations

import argparse
import sqlite3
from pathlib import Path
from typing import Iterable, Sequence

BASE_DIR = Path(__file__).resolve().parent.parent
DB_PATH = BASE_DIR / "data" / "frequency" / "frequency.sqlite"

TABLE_CONFIG: dict[str, Sequence[str]] = {
    "subtlex": ["word"],
    "multilex": ["Palabra"],
    "gpt_familiarity": ["Word"],
    "gpt_affect": ["Word"],
    "lemma40k": ["lemma"],
    "form40k": ["word", "lemma"],
    "form200k": ["word"],
}


def fetch_rows(conn: sqlite3.Connection, table: str, columns: Iterable[str], term: str):
    """Return rows where any column (lowercased) matches the search term."""
    results = []
    for column in columns:
        query = f'SELECT * FROM "{table}" WHERE lower("{column}") = ?'
        rows = conn.execute(query, (term.lower(),)).fetchall()
        results.extend(rows)
    return results


def format_rows(cursor: sqlite3.Cursor, rows: list[tuple]) -> list[str]:
    if not rows:
        return []
    column_names = [description[0] for description in cursor.description]
    formatted = []
    for row in rows:
        pairs = [f"{col}={value}" for col, value in zip(column_names, row)]
        formatted.append(", ".join(pairs))
    return formatted


def lookup_term(conn: sqlite3.Connection, term: str, tables: Sequence[str]) -> list[str]:
    output_lines: list[str] = []
    for table in tables:
        if table not in TABLE_CONFIG:
            continue
        cursor = conn.cursor()
        rows = fetch_rows(conn, table, TABLE_CONFIG[table], term)
        if not rows:
            continue
        output_lines.append(f"[{table}]")
        for row in rows:
            cursor.execute(f"PRAGMA table_info('{table}')")
            columns = [info[1] for info in cursor.fetchall()]
            pairs = [f"{col}={value}" for col, value in zip(columns, row)]
            output_lines.append("  " + ", ".join(pairs))
    return output_lines


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Lookup Spanish frequency data.")
    parser.add_argument("terms", nargs="+", help="Word(s) or lemma(s) to search.")
    parser.add_argument(
        "--tables",
        default=",".join(TABLE_CONFIG.keys()),
        help="Comma-separated list of tables to search (default: all).",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    tables = [name.strip() for name in args.tables.split(",") if name.strip()]

    if not DB_PATH.exists():
        raise SystemExit(
            "frequency.sqlite not found. Run scripts/build_frequency_index.py first."
        )

    conn = sqlite3.connect(DB_PATH)

    for term in args.terms:
        print(f"=== {term} ===")
        lines = lookup_term(conn, term, tables)
        if not lines:
            print("  (no results)")
            continue
        for line in lines:
            print(line)

    conn.close()


if __name__ == "__main__":
    main()
